### ISSUE TITLE
Fix (Re-add) App Screenshots Drag

### ISSUE THREAD

**Issue by sGerli** [pebble-dev/rebble-store#81]
Re add js script to enable draggable screenshots as seen in the preview.

**Comment by sGerli** [comment]
@Zetaphor We were using [dragscroll.js](https://github.com/pebble-dev/rebble-store/blob/master/src/app-details.html#L212) for this, what's the appropriate way of adding this to vue?

**Comment by Zetaphor** [comment]
@sGerli, I'll take a look in the morning at how you did it on the old site and work up an implementation

**Comment by sGerli** [comment]
Here's the link to the script's page https://github.com/asvd/dragscroll it just needs to load it's js and then looks for a div with `class="dragscroll"`.

**Comment by Zetaphor** [comment]
Fixed in #84. There's a better way to do this using vue-strap, I'll have to revisit this later.

**Comment by sGerli** [comment]
I have been testing our last Vue build and I noticed that this only works if you go directly into http://store.rebble.io/#/app-details , It doesn't work if you go to any other page and then into app-details.

**Comment by sGerli** [comment]
Reopening as this issue still exists, I didn't test correctly last time.

**Comment by MHC03** [comment]
This may be solveable with an entire [new package](https://github.com/donmbelembe/vue-dragscroll). [Here](https://donmbelembe.github.io/vue-dragscroll/) are also some working example of the vue-dragscroll package.

Do I need to have the backend to get those pictures aligned like in the rebble io store page?

I would like to give the package a try, if noone is currently working on this.

**Comment by sGerli** [comment]
I tried to use that package but I wasn't able to make it work properly, maybe I made an error while trying to implement it
